name: antlr4dart_tool
version: 0.5.0
author: Tiago Mazzutti <tiagomzt@gmail.com>
description: ANTLR4 tool with Dart target suport.
homepage: https://github.com/tiagomazzutti/antlr4dart.git
dependencies:
  antlr4dart:
    path: antlr4dart-runtime
  test: ^1.6.8
  bit_set: 
    git: https://github.com/skalkin/bit_set.git 
  collection: any  

environment:
  sdk: ">=2.2.2 <3.0.0"