name: antlr4dart-tool
author: Tiago Mazzutti <tiagomzt@gmail.com>
version: 0.1.0
homepage: https://github.com/tiagomazzutti/antlr4dart.git
description: ANTLR4 tool with Dart target suport.
dependencies:
  antlr4dart:
    path: antlr4dart-runtime
  fixnum: any
  logging: '>=0.3.1+1 <0.3.2'
  unittest: any
