name: antlr4dart_tool
version: 0.5.0
author: Tiago Mazzutti <tiagomzt@gmail.com>
description: ANTLR4 tool with Dart target suport.
homepage: https://github.com/tiagomazzutti/antlr4dart.git
dependencies:
  antlr4dart:
    path: antlr4dart-runtime
  bignum: any
  browser: any
  unittest: any
